# Generated by Django 5.1.4 on 2024-12-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0004_orderstatus_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе менеджера'), ('confirmed', 'Подтвержден'), ('assembling', 'В сборке'), ('in_delivery', 'В доставке'), ('completed', 'Завершен'), ('canceled', 'Отменён')], max_length=20, unique=True),
        ),
    ]
