# Generated by Django 5.1.4 on 2025-01-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0008_alter_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstatus',
            name='status',
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='name',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
