# Generated by Django 5.1.4 on 2025-01-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0009_remove_orderstatus_status_orderstatus_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
